In [6]:
#1. Write a Python code to import NumPy.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
#2. Write a Python program to create 3x3 matrix with values ranging from 5 to 13.
import numpy as np

n=np.arange(5,14).reshape(3,3)
print(n)


[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [12]:
#3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
import numpy as np

n=np.zeros(10)
n[6]=11
print(n)


[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [14]:
#4. Write a Python program to create a array with values ranging from 12 to 38.
import numpy as np

n=np.arange(12,39)
print(n)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [15]:
#6. Write a Python program to reverse an array so that first element becomes last.
n=np.array([1,2,3,4])
reverse= n[::-1]
print(reverse)

[4 3 2 1]


In [17]:
#7. Write a Python program to an array converted to a float type.
import numpy as np

n = np.array([1, 2, 3, 4])
print(n.astype(float))


[1. 2. 3. 4.]


In [20]:
#8. Write a Python program to create a 2d array with 1 on the border and 0 inside.
import numpy as np

n=np.ones((4,4))
n[1:-1,1:-1]=0
print(n)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [23]:
#9. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
import numpy as np

def checkerboard(n):
	print("Checkerboard pattern:")
	x = np.zeros((n, n), dtype=int)
	x[1::2, ::2] = 1
	x[::2, 1::2] = 1
	for i in range(n):
		for j in range(n):
			print(x[i][j], end=" ")
		print()

n = 8
print (checkerboard(n))


Checkerboard pattern:
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
None


In [30]:
#10. Write a Python program to convert a list and tuple into arrays.
import numpy as np

lst=[1,2,3,4]
print(lst)
tup=5,6,7,8
print(tup)
arr1=np.asarray(lst)
arr2=np.asarray(tup)
print(arr1)
print(arr2)

[1, 2, 3, 4]
(5, 6, 7, 8)
[1 2 3 4]
[5 6 7 8]


In [40]:
#11. Write a Python program to append values to the end of an array. 
import numpy as np

n=np.arange(2,11)
print(n)
m=np.arange(11,13)
print(m)
print(np.append(n,m))


[ 2  3  4  5  6  7  8  9 10]
[11 12]
[ 2  3  4  5  6  7  8  9 10 11 12]


In [54]:
#12. Write a Python program to create an empty and a full array. 
import numpy as np

emp=np.empty((3,4),dtype=int)
print("Empty Array:")
print(emp)

full=np.full((3,3),3,dtype=int)
print("Full Array:")
print(full)


Empty Array:
[[         0 1072693248          0 1073741824]
 [         0 1074266112          0 1074266112]
 [         0 1074790400          0 1075052544]]
Full Array:
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [55]:
#13. Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.
import numpy as np

celsius_temps = [0, 12, 45.21, 34, 99.91]
celsius_array = np.array(celsius_temps)
fahrenheit_array = (celsius_array * 9/5) + 32

print(f"Fahrenheit: {fahrenheit_array}")


Fahrenheit: [ 32.     53.6   113.378  93.2   211.838]


In [59]:
#14. Write a Python program to find the real and imaginary parts of an array of complex numbers.
import numpy as np

complex=np.array([1+5j,2-6j,3+7j,4-8j])
for i in range(len(complex)):
    print("Complex No:",complex[i])
    print("Real part:",complex[i].real)
    print("Imaginary part:",complex[i].imag,"\n")


Complex No: (1+5j)
Real part: 1.0
Imaginary part: 5.0 

Complex No: (2-6j)
Real part: 2.0
Imaginary part: -6.0 

Complex No: (3+7j)
Real part: 3.0
Imaginary part: 7.0 

Complex No: (4-8j)
Real part: 4.0
Imaginary part: -8.0 



In [61]:
#15. Write a Python program to test whether each element of a 1-D array is also present in a second array.
import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])

equal=np.array_equal(arr1,arr2)
print(equal)



True


In [62]:
#16. Write a Python program to find common values between two arrays.
import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
common=np.intersect1d(arr1,arr2)
print("Common elements are:")
print(common)

Common elements are:
[3 4]


In [63]:
#17. Write a Python program to get the unique elements of an array.
import numpy as np

arr1=np.array([1,2,2,3,3,4])
unique=np.unique(arr1)
print("Unique element(s) of array:")
print(unique)

Unique element(s) of array:
[1 2 3 4]


In [65]:
#18. Write a Python program to test if all elements in an array evaluate to True.
import numpy as np

a = int(input("Enter the size of the array: "))
my_list = []
for i in range(a):
    x = float(input(f"Enter element {i + 1}: "))
    my_list.append(x)

arr1 = np.array(my_list)
print("User input array:", arr1)
res=np.all(arr1)
print("Evaluation of array :",res)



User input array: [1. 2. 3. 4.]
Evaluation of array : True


In [66]:
#19. Write a Python program to test whether any array element along a given axis evaluates to True.
import numpy as np

print(np.any([[False,False],[False,False]])) 
print(np.any([[True,True],[True,True]]))  

print(np.any([10, 20, 0, -50])) 
print(np.any([10, 20, -50])) 

False
True
True
True


In [72]:
#20. Write a Python program to repeat elements of an array.
import numpy as np

arr1=np.array([[1,2,3,4]
               ,[5,6,7,0]])
rep=np.repeat(arr1,2,axis=1)
print(rep)

[[1 1 2 2 3 3 4 4]
 [5 5 6 6 7 7 0 0]]


In [74]:
#21. Write a Python program to find the indices of the maximum and minimum values along the given axis of an array.
import numpy as np

arr1=np.array([1,2,3,4,5])

max_index=np.argmax(arr1)
print("Index of maximum value:",max_index)

min_index=np.argmin(arr1)
print("Index of minimum value:",min_index)

Index of maximum value: 4
Index of minimum value: 0


In [78]:
#22. Write a Python program compare two arrays using numpy.
import numpy as np

arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
compare=arr1==arr2
res=compare.all()
print(res)

True


In [79]:
#23. Write a Python program to save a NumPy array to a text file.
import numpy as np

arr1 = np.array(np.random.randint(1, 100, 7))

with open('readme.txt', 'w') as f:
    f.write(' '.join(map(str, arr1)))


In [80]:
#24. Write a Python program to create a contiguous flattened array.
import numpy as np

arr1=np.array([[1,2,3,4],[5,6,7,8]])
print("Original Array:\n",arr1)

con_flat_arr=np.ravel(arr1)
print("Contiguous Flattened Array:",con_flat_arr)

Original Array:
 [[1 2 3 4]
 [5 6 7 8]]
Contiguous Flattened Array: [1 2 3 4 5 6 7 8]


In [88]:
#25. Write a program to perform addition,minimum and maximum values from a 3D array.
import numpy as np

arr1=np.arange(2,11).reshape(3,3)
sum= np.sum(arr1,axis=0)
minimum= np.min(arr1,axis=1)
maximum= np.max(arr1,axis=1)

print("Original Array:")
print(arr1)
print("Sum of array:")
print(sum)
print("\nMinumum value:")
print(minimum)
print("\nMaximum value:")
print(maximum)


Original Array:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Sum of array:
[15 18 21]

Minumum value:
[2 5 8]

Maximum value:
[ 4  7 10]
