In [1]:
#1
class Person:
    def __init__(self, name, designation):
        self.name = name
        self.designation = designation

    def learn(self):
        print(self.name, "is learning.")

    def walk(self):
        print(self.name, "is walking.")

    def eat(self):
        print(self.name, "is eating.")


class Programmer(Person):
    def __init__(self, name, designation, company_name):
        super().__init__(name, designation)
        self.company_name = company_name

    def coding(self):
        print(self.name, "is coding at", self.company_name)


class Dancer(Person):
    def __init__(self, name, designation, group_name):
        super().__init__(name, designation)
        self.group_name = group_name

    def dancing(self):
        print(self.name, "is dancing with group", self.group_name)


class Singer(Person):
    def __init__(self, name, designation, band_name):
        super().__init__(name, designation)
        self.band_name = band_name

    def singing(self):
        print(self.name, "is singing with band", self.band_name)

    def play_guitar(self):
        print(self.name, "is playing guitar with band", self.band_name)


if __name__ == "__main__":
    programmer = Programmer("Alice", "Software Engineer", "TechCorp")
    programmer.learn()
    programmer.walk()
    programmer.eat()
    programmer.coding()

    print()

    dancer = Dancer("Bob", "Dance Instructor", "Fusion Crew")
    dancer.learn()
    dancer.walk()
    dancer.eat()
    dancer.dancing()

    print()

    singer = Singer("Charlie", "Lead Vocalist", "Rockstars")
    singer.learn()
    singer.walk()
    singer.eat()
    singer.singing()
    singer.play_guitar()


Alice is learning.
Alice is walking.
Alice is eating.
Alice is coding at TechCorp

Bob is learning.
Bob is walking.
Bob is eating.
Bob is dancing with group Fusion Crew

Charlie is learning.
Charlie is walking.
Charlie is eating.
Charlie is singing with band Rockstars
Charlie is playing guitar with band Rockstars


In [29]:
#2
import pandas as pd

branch1_data = pd.read_csv('branch1_sales.csv')
branch2_data = pd.read_csv('branch2_sales.csv')

total_sales = pd.concat([branch1_data, branch2_data],ignore_index=True)
sum= total_sales.iloc[[0,3]].sum()
#sum.name='games'
total_sales=pd.concat([total_sales,pd.DataFrame([sum])],ignore_index=True)
total_sales.rename(columns={'GamesGAMES':'games'},inplace=True)
total_sales.drop([0,3],inplace=True)
total_sales.reset_index(drop=True,inplace=True)
total_sales=pd.melt(total_sales,id_vars=['PRODUCT_TYPE'])
total_sales['SOLD_DATE']=total_sales['variable']
total_sales['QTY_SOLD']=total_sales['value']
total_sales.drop(['variable','value'],axis=1)
#total_sales.iloc[:,[1,0,2]]
total_sales=total_sales.loc[:,['SOLD_DATE','PRODUCT_TYPE','QTY_SOLD']]


final= total_sales.to_csv('final.csv', index=False)

print("Data transformation and aggregation completed. Output saved to final.csv.")



Data transformation and aggregation completed. Output saved to final.csv.


In [38]:
#3
import pandas as pd
import numpy as np
import datetime as dt
import geopy.distance
import pyodbc
from sqlalchemy import create_engine

#Getting csv file and converting the values into datetime fomrat
df =pd.read_csv('Q1.csv')
df['Start Time']=df['Start Time'].astype('datetime64[ns]')
df['End Time']=df['End Time'].astype('datetime64[ns]')

#finding the duration and storing it in the Duration column
df['Duration']=(df['End Time']-df['Start Time']).dt.total_seconds().astype(int)

#checking the weekends and storing the values in is_weekend columns
df['is_weekend']=df['Start Time'].dt.day_of_week.isin([5,6]).astype(int)

#checking the hour of the day and storing it in the column hour_of_the_day
df['hour_of_the_day']=df['Start Time'].dt.hour

#finding the distance between start and end coordinates (latitude and longitude) and soring it in the distance column
def cal_distance(row):
    start=(row['Start Latitude'],row['Start Longitude'])
    end=(row['End Latitude'],row['End Longitude'])
    return geopy.distance.geodesic(start,end).kilometers
df['distance']=df.apply(cal_distance,axis=1)

#connecting to sql server and loading the output as sql table
server = 'SS-SQL-01'
database = 'Intern2024'
username = 'B2024_SSelvar1'
password = 'Bazinga_02'

cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
df.to_sql('Final',con = engine,if_exists='replace',index=False)
cnxn.close()


In [39]:
df

Start Time            End Time  Start Latitude  Start Longitude  \
0 2015-04-15 13:12:00 2015-04-15 13:26:00      -74.003939        40.742894   
1 2015-04-23 22:04:00 2015-04-23 22:16:00      -73.973864        40.752194   
2 2015-04-18 03:19:00 2015-04-18 03:54:00      -73.954406        40.764420   
3 2015-04-18 21:49:00 2015-04-18 22:11:00      -73.962345        40.767215   
4 2015-04-14 07:57:00 2015-04-14 08:14:00      -74.004657        40.707434   
5 2015-04-26 17:49:00 2015-04-26 18:14:00      -73.995571        40.716019   
6 2015-04-30 22:14:00 2015-04-30 22:17:00      -74.008049        40.740404   
7 2015-04-13 20:32:00 2015-04-13 20:43:00      -73.942793        40.811667   
8 2015-04-23 23:22:00 2015-04-23 23:28:00      -73.972762        40.752850   
9 2015-04-23 15:07:00 2015-04-23 15:28:00      -73.981350        40.740912   

   End Latitude  End Longitude  Duration  is_weekend  hour_of_the_day  \
0    -73.993369      40.734247       840           0               13   
1    -73.958701      40.772533       720           0               22   
2    -73.970780      40.758350      2100           1                3   
3    -73.975512      40.756867      1320           1               21   
4    -73.999369      40.721517      1020           0                7   
5    -73.999968      40.743319      1500           1               17   
6    -73.931014      40.765785       180           0               22   
7    -74.002690      40.733645       660           0               20   
8    -73.956535      40.805865       360           0               23   
9    -73.975187      40.751382      1260           0               15   

   distance  
0  1.209353  
1  1.804833  
2  1.837036  
3  1.503789  
4  0.732231  
5  0.973177  
6  8.633266  
7  7.104581  
8  2.440089  
9  0.759769

In [36]:
#4
import pandas as pd
import pyodbc
import sqlalchemy

server = 'SS-SQL-01'
database = 'Northwind'
username = 'B2024_SSelvar1'
password = 'Bazinga_02'

# Establishing the connection and reading data directly into DataFrame
cnxn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
query1='SELECT* FROM Orders'
df_Orders= pd.read_sql(query1,cnxn)
query2='SELECT* FROM Order_details'
df_Order_Details= pd.read_sql(query2,cnxn)

#final_join= pd.concat([df_Orders,df_Order_Details],ignore_index=True)
final_join = pd.merge(df_Orders, df_Order_Details, on="OrderID", how="inner")

print(final_join)
cnxn.close()

C:\Users\SivaPrakashSelvaraj\AppData\Local\Temp\ipykernel_13016\2086294869.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Orders= pd.read_sql(query1,cnxn)
C:\Users\SivaPrakashSelvaraj\AppData\Local\Temp\ipykernel_13016\2086294869.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_Order_Details= pd.read_sql(query2,cnxn)


      OrderID CustomerID  EmployeeID  OrderDate RequiredDate ShippedDate  \
0       10248      VINET           5 1996-07-04   1996-08-01  1996-07-16   
1       10248      VINET           5 1996-07-04   1996-08-01  1996-07-16   
2       10248      VINET           5 1996-07-04   1996-08-01  1996-07-16   
3       10249      TOMSP           6 1996-07-05   1996-08-16  1996-07-10   
4       10249      TOMSP           6 1996-07-05   1996-08-16  1996-07-10   
...       ...        ...         ...        ...          ...         ...   
2150    11077      RATTC           1 1998-05-06   1998-06-03         NaT   
2151    11077      RATTC           1 1998-05-06   1998-06-03         NaT   
2152    11077      RATTC           1 1998-05-06   1998-06-03         NaT   
2153    11077      RATTC           1 1998-05-06   1998-06-03         NaT   
2154    11077      RATTC           1 1998-05-06   1998-06-03         NaT   

      ShipVia  Freight                    ShipName         ShipAddress  \
0           3

In [1]:
#5
import pandas as pd
import numpy as np
'''
input_list = [9, 4, 4, 7, 1, 8, 4, 7, 3, 0, 2, 5, 7, 3, 7, 2, 6, 8, 4, 6, 7, 1, 3, 2]
sorted_unique_list = sorted(set(input_list))
lst = sorted_unique_list.copy()

for num in input_list:
    if lst.count(num) < input_list.count(num):
        lst.append(num)'''
def rearrange_list(input_list):
    sorted_list = sorted(input_list)

    even_nums = []
    odd_nums = []

    for num in sorted_list:
        if num % 2 == 0:
            even_nums.append(num)
        else:
            odd_nums.append(num)

    rearranged_list = even_nums + odd_nums

    return rearranged_list

input_list = [9,4,4,7,1,8,4,7,3,0,2,5,7,3,7,2,6,8,4,6,7,1,3,2]
output_list = rearrange_list(input_list)
print("Sorted List:",output_list)

arr= np.array(output_list).reshape(6,4)
print("Converted 6x4 array:",arr)

df=pd.DataFrame(arr,index=['a','b','c','d','e','f'],columns=['A','B','C','D'])
print("Data Frame with index 'a' to 'f' and column name 'A' to 'F' :")
print(df)

[0, 2, 2, 2, 4, 4, 4, 4, 6, 6, 8, 8, 1, 1, 3, 3, 3, 5, 7, 7, 7, 7, 7, 9]
Sorted List: [0, 2, 2, 2, 4, 4, 4, 4, 6, 6, 8, 8, 1, 1, 3, 3, 3, 5, 7, 7, 7, 7, 7, 9]
Converted 6x4 array: [[0 2 2 2]
 [4 4 4 4]
 [6 6 8 8]
 [1 1 3 3]
 [3 5 7 7]
 [7 7 7 9]]
Data Frame with index 'a' to 'f' and column name 'A' to 'F' :
   A  B  C  D
a  0  2  2  2
b  4  4  4  4
c  6  6  8  8
d  1  1  3  3
e  3  5  7  7
f  7  7  7  9


In [5]:
#6
lst=[66,34,76,47,20,86,10,81,75,73,51,28,1,1,9,83,30,47,67,4]
arr=np.array(lst).reshape(5,4)
df=pd.DataFrame(arr,index=[0,1,2,3,4],columns=['a','b','c','d'])
print("Original Data Frame:")
print(df)

df['a_lag']= df['a'].shift(1)

df['d_lead']= df['d'].shift(-1)

print("Lead and Lag added Data Frames:")
print(df)


Original Data Frame:
    a   b   c   d
0  66  34  76  47
1  20  86  10  81
2  75  73  51  28
3   1   1   9  83
4  30  47  67   4
Lead and Lag added Data Frames:
    a   b   c   d  a_lag  d_lead
0  66  34  76  47    NaN    81.0
1  20  86  10  81   66.0    28.0
2  75  73  51  28   20.0    83.0
3   1   1   9  83   75.0     4.0
4  30  47  67   4    1.0     NaN


In [5]:
#7
import datetime
df1= pd.read_csv('student_marks.csv')
#df1['DOB']=df1['DOB'].astype('datetime64[ns]')
#a
def calculate_age(dob):
    dob = datetime.datetime.strptime(dob, '%d-%m-%Y')
    today = datetime.datetime.today()
    return today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))

df1['age'] = df1['DOB'].apply(calculate_age)
print(df1[['Name', 'DOB', 'age']])

#b
def calculate_average(row):
    subjects = ['Maths', 'Physics', 'Chemistry', 'English', 'Biology', 'Economics', 'History', 'Civics']
    marks = [row[subject] for subject in subjects if pd.notna(row[subject])]
    if marks:
        return sum(marks) / len(marks)
    else:
        return 0

def assign_grade(average):
    if average >= 90:
        return 'A'
    elif average >= 80:
        return 'B'
    elif average >= 70:
        return 'C'
    elif average >= 60:
        return 'D'
    else:
        return 'F'

df1['Average'] = df1.apply(calculate_average, axis=1)
df1['Grade'] = df1['Average'].apply(assign_grade)
print(df1)

#c
passed_students= df1[df1['Grade']<='D']
passed_students.to_csv('passed_students.csv',index=False)
print("\nFile Saved Successfully")

       Name         DOB  age
0      John  05-04-1988   36
1    Suresh  04-05-1987   37
2    Ramesh  25-05-1989   34
3   Jessica  12-08-1990   33
4  Jennifer  02-09-1989   34
5  Praveena  10-11-1987   36
6      Sean  05-10-1991   32
7     Ramya  12-09-1990   33
8      Jake  06-03-1989   35
9     David  03-12-1987   36
       Name Gender         DOB  Maths  Physics  Chemistry  English  Biology  \
0      John      M  05-04-1988     55       45       56.0       87       21   
1    Suresh      M  04-05-1987     75       55        NaN       64       90   
2    Ramesh      M  25-05-1989     25       54       89.0       76       95   
3   Jessica      F  12-08-1990     78       55       86.0       63       54   
4  Jennifer      F  02-09-1989     58       96       78.0       46       96   
5  Praveena      F  10-11-1987     56       34       42.0       76       23   
6      Sean      M  05-10-1991     45       56       32.0       78       45   
7     Ramya      F  12-09-1990     90       55   